export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-primary": "#ffffff",
        "tertiary-container": "#331200",
        "outline": "#76777d",
        "primary-container": "#131b2e",
        "on-error-container": "#93000a",
        "surface": "#f8f9ff",
        "inverse-primary": "#bec6e0",
        "secondary": "#5e5e5e",
        "surface-container-high": "#dce9ff",
        "on-background": "#0d1c2e",
        "surface-tint": "#565e74",
        "secondary-fixed": "#e3e2e1",
        "secondary-fixed-dim": "#c7c6c5",
        "outline-variant": "#c6c6cd",
        "secondary-container": "#e0dfdf",
        "on-secondary-fixed": "#1a1c1c",
        "surface-dim": "#ccdbf3",
        "inverse-surface": "#233144",
        "surface-container": "#e6eeff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "on-surface-variant": "#45464d",
        "surface-container-highest": "#d5e3fc",
        "on-primary-container": "#7c839b",
        "on-primary-fixed": "#131b2e",
        "on-tertiary-container": "#cf6721",
        "surface-container-low": "#eff4ff",
        "background": "#f8f9ff",
        "surface-variant": "#d5e3fc",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "on-tertiary-fixed-variant": "#763300",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#331200",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb68e",
        "on-surface": "#0d1c2e",
        "primary-fixed-dim": "#bec6e0",
        "tertiary": "#000000",
        "tertiary-fixed": "#ffdbca",
        "primary": "#000000",
        "primary-fixed": "#dae2fd",
        "on-secondary-container": "#626362",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-fixed-variant": "#464746"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "gutter": "32px",
        "container-max": "1120px",
        "stack-lg": "64px",
        "stack-md": "24px",
        "stack-sm": "12px",
        "margin": "40px"
      },
      "fontFamily": {
        "display-lg": ["Newsreader"],
        "label-md": ["Work Sans"],
        "body-lg": ["Newsreader"],
        "headline-md": ["Newsreader"],
        "body-md": ["Newsreader"],
        "label-sm": ["Work Sans"],
        "headline-lg": ["Newsreader"]
      },
      "fontSize": {
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "body-lg": ["20px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}],
        "body-md": ["17px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "1.4", "letterSpacing": "0.08em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "500"}]
      }
    },
    screens: {
      'xs': '400px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
  },
  plugins: [],
}
